# TCL File Generated by Component Editor 18.0
# Fri May 24 16:41:31 CST 2024
# DO NOT MODIFY


# 
# control "Control" v1.1
# Loigen Sodian 2024.05.24.16:41:31
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module control
# 
set_module_property DESCRIPTION ""
set_module_property NAME control
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Loigen Sodian"
set_module_property DISPLAY_NAME Control
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Control
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Control.sv SYSTEM_VERILOG PATH Control.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL Control
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Control.sv SYSTEM_VERILOG PATH Control.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point Clk
# 
add_interface Clk clock end
set_interface_property Clk clockRate 50000000
set_interface_property Clk ENABLED true
set_interface_property Clk EXPORT_OF ""
set_interface_property Clk PORT_NAME_MAP ""
set_interface_property Clk CMSIS_SVD_VARIABLES ""
set_interface_property Clk SVD_ADDRESS_GROUP ""

add_interface_port Clk Clk clk Input 1


# 
# connection point Reset
# 
add_interface Reset reset end
set_interface_property Reset associatedClock Clk
set_interface_property Reset synchronousEdges DEASSERT
set_interface_property Reset ENABLED true
set_interface_property Reset EXPORT_OF ""
set_interface_property Reset PORT_NAME_MAP ""
set_interface_property Reset CMSIS_SVD_VARIABLES ""
set_interface_property Reset SVD_ADDRESS_GROUP ""

add_interface_port Reset Reset reset Input 1


# 
# connection point PR_MM_MASTER
# 
add_interface PR_MM_MASTER avalon start
set_interface_property PR_MM_MASTER addressUnits WORDS
set_interface_property PR_MM_MASTER associatedClock Clk
set_interface_property PR_MM_MASTER associatedReset Reset
set_interface_property PR_MM_MASTER bitsPerSymbol 8
set_interface_property PR_MM_MASTER burstOnBurstBoundariesOnly false
set_interface_property PR_MM_MASTER burstcountUnits WORDS
set_interface_property PR_MM_MASTER doStreamReads false
set_interface_property PR_MM_MASTER doStreamWrites false
set_interface_property PR_MM_MASTER holdTime 0
set_interface_property PR_MM_MASTER linewrapBursts false
set_interface_property PR_MM_MASTER maximumPendingReadTransactions 0
set_interface_property PR_MM_MASTER maximumPendingWriteTransactions 0
set_interface_property PR_MM_MASTER readLatency 0
set_interface_property PR_MM_MASTER readWaitTime 1
set_interface_property PR_MM_MASTER setupTime 0
set_interface_property PR_MM_MASTER timingUnits Cycles
set_interface_property PR_MM_MASTER writeWaitTime 0
set_interface_property PR_MM_MASTER ENABLED true
set_interface_property PR_MM_MASTER EXPORT_OF ""
set_interface_property PR_MM_MASTER PORT_NAME_MAP ""
set_interface_property PR_MM_MASTER CMSIS_SVD_VARIABLES ""
set_interface_property PR_MM_MASTER SVD_ADDRESS_GROUP ""

add_interface_port PR_MM_MASTER ADDRESS_PR address Output 10
add_interface_port PR_MM_MASTER BYTE_EN_PR byteenable Output 4
add_interface_port PR_MM_MASTER CS_PR chipselect Output 1
add_interface_port PR_MM_MASTER READ_PR read Output 1
add_interface_port PR_MM_MASTER WRITE_PR write Output 1
add_interface_port PR_MM_MASTER READDATA_PR readdata Input 32
add_interface_port PR_MM_MASTER WRITEDATA_PR writedata Output 32
add_interface_port PR_MM_MASTER WAIT_REQUEST_PR waitrequest Input 1


# 
# connection point DC_MM_MASTER
# 
add_interface DC_MM_MASTER avalon start
set_interface_property DC_MM_MASTER addressUnits WORDS
set_interface_property DC_MM_MASTER associatedClock Clk
set_interface_property DC_MM_MASTER associatedReset Reset
set_interface_property DC_MM_MASTER bitsPerSymbol 8
set_interface_property DC_MM_MASTER burstOnBurstBoundariesOnly false
set_interface_property DC_MM_MASTER burstcountUnits WORDS
set_interface_property DC_MM_MASTER doStreamReads false
set_interface_property DC_MM_MASTER doStreamWrites false
set_interface_property DC_MM_MASTER holdTime 0
set_interface_property DC_MM_MASTER linewrapBursts false
set_interface_property DC_MM_MASTER maximumPendingReadTransactions 0
set_interface_property DC_MM_MASTER maximumPendingWriteTransactions 0
set_interface_property DC_MM_MASTER readLatency 0
set_interface_property DC_MM_MASTER readWaitTime 1
set_interface_property DC_MM_MASTER setupTime 0
set_interface_property DC_MM_MASTER timingUnits Cycles
set_interface_property DC_MM_MASTER writeWaitTime 0
set_interface_property DC_MM_MASTER ENABLED true
set_interface_property DC_MM_MASTER EXPORT_OF ""
set_interface_property DC_MM_MASTER PORT_NAME_MAP ""
set_interface_property DC_MM_MASTER CMSIS_SVD_VARIABLES ""
set_interface_property DC_MM_MASTER SVD_ADDRESS_GROUP ""

add_interface_port DC_MM_MASTER ADDRESS_DC address Output 12
add_interface_port DC_MM_MASTER CS_DC chipselect Output 1
add_interface_port DC_MM_MASTER READ_DC read Output 1
add_interface_port DC_MM_MASTER WRITE_DC write Output 1
add_interface_port DC_MM_MASTER READDATA_DC readdata Input 16
add_interface_port DC_MM_MASTER WRITEDATA_DC writedata Output 16
add_interface_port DC_MM_MASTER WAIT_REQUEST_DC waitrequest Input 1


# 
# connection point controls
# 
add_interface controls conduit end
set_interface_property controls associatedClock Clk
set_interface_property controls associatedReset Reset
set_interface_property controls ENABLED true
set_interface_property controls EXPORT_OF ""
set_interface_property controls PORT_NAME_MAP ""
set_interface_property controls CMSIS_SVD_VARIABLES ""
set_interface_property controls SVD_ADDRESS_GROUP ""

add_interface_port controls check check Input 1
add_interface_port controls valid valid Input 1
add_interface_port controls done done Input 1
add_interface_port controls Clean clean Output 1
add_interface_port controls Run run Output 1


# 
# connection point vga_clk
# 
add_interface vga_clk clock end
set_interface_property vga_clk clockRate 25000000
set_interface_property vga_clk ENABLED true
set_interface_property vga_clk EXPORT_OF ""
set_interface_property vga_clk PORT_NAME_MAP ""
set_interface_property vga_clk CMSIS_SVD_VARIABLES ""
set_interface_property vga_clk SVD_ADDRESS_GROUP ""

add_interface_port vga_clk VGA_CLK clk Input 1

