# TCL File Generated by Component Editor 18.0
# Fri May 24 18:26:54 CST 2024
# DO NOT MODIFY


# 
# pixel_render "Pixel Render" v1.1
# Loigen Sodian 2024.05.24.18:26:53
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pixel_render
# 
set_module_property DESCRIPTION ""
set_module_property NAME pixel_render
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Loigen Sodian"
set_module_property DISPLAY_NAME "Pixel Render"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL PixelRender
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file PixelRender.sv SYSTEM_VERILOG PATH PixelRender.sv TOP_LEVEL_FILE
add_fileset_file PixelOCM.qip OTHER PATH PixelOCM.qip
add_fileset_file Palette.sv SYSTEM_VERILOG PATH Palette.sv
add_fileset_file PixelOCM.v VERILOG PATH PixelOCM.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL PixelRender
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file PixelRender.sv SYSTEM_VERILOG PATH PixelRender.sv
add_fileset_file PixelOCM.qip OTHER PATH PixelOCM.qip
add_fileset_file Palette.sv SYSTEM_VERILOG PATH Palette.sv
add_fileset_file PixelOCM.v VERILOG PATH PixelOCM.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point Clk
# 
add_interface Clk clock end
set_interface_property Clk clockRate 50000000
set_interface_property Clk ENABLED true
set_interface_property Clk EXPORT_OF ""
set_interface_property Clk PORT_NAME_MAP ""
set_interface_property Clk CMSIS_SVD_VARIABLES ""
set_interface_property Clk SVD_ADDRESS_GROUP ""

add_interface_port Clk Clk clk Input 1


# 
# connection point Reset
# 
add_interface Reset reset end
set_interface_property Reset associatedClock Clk
set_interface_property Reset synchronousEdges DEASSERT
set_interface_property Reset ENABLED true
set_interface_property Reset EXPORT_OF ""
set_interface_property Reset PORT_NAME_MAP ""
set_interface_property Reset CMSIS_SVD_VARIABLES ""
set_interface_property Reset SVD_ADDRESS_GROUP ""

add_interface_port Reset Reset reset Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock Clk
set_interface_property avalon_slave associatedReset Reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave AVL_ADDRESS address Input 10
add_interface_port avalon_slave AVL_BYTE_EN byteenable Input 4
add_interface_port avalon_slave AVL_CS chipselect Input 1
add_interface_port avalon_slave AVL_READDATA readdata Output 32
add_interface_port avalon_slave AVL_WRITEDATA writedata Input 32
add_interface_port avalon_slave AVL_READ read Input 1
add_interface_port avalon_slave AVL_WRITE write Input 1
add_interface_port avalon_slave AVL_WAIT_REQUEST waitrequest Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point draw_control
# 
add_interface draw_control conduit end
set_interface_property draw_control associatedClock Clk
set_interface_property draw_control associatedReset Reset
set_interface_property draw_control ENABLED true
set_interface_property draw_control EXPORT_OF ""
set_interface_property draw_control PORT_NAME_MAP ""
set_interface_property draw_control CMSIS_SVD_VARIABLES ""
set_interface_property draw_control SVD_ADDRESS_GROUP ""

add_interface_port draw_control RE_OCM re_ocm Input 1
add_interface_port draw_control WritePixel writepixel Input 8
add_interface_port draw_control WriteX writex Input 10
add_interface_port draw_control WriteY writey Input 10
add_interface_port draw_control DrawX drawx Input 10
add_interface_port draw_control DrawY drawy Input 10
add_interface_port draw_control StartPoint startp Output 13
add_interface_port draw_control EndPoint endp Output 13
add_interface_port draw_control WE we Input 1
add_interface_port draw_control Run run Input 1


# 
# connection point vga
# 
add_interface vga conduit end
set_interface_property vga associatedClock Clk
set_interface_property vga associatedReset Reset
set_interface_property vga ENABLED true
set_interface_property vga EXPORT_OF ""
set_interface_property vga PORT_NAME_MAP ""
set_interface_property vga CMSIS_SVD_VARIABLES ""
set_interface_property vga SVD_ADDRESS_GROUP ""

add_interface_port vga VGA_R red Output 8
add_interface_port vga VGA_G green Output 8
add_interface_port vga VGA_B blue Output 8
add_interface_port vga blank blank Input 1


# 
# connection point VGA_CLK
# 
add_interface VGA_CLK clock end
set_interface_property VGA_CLK clockRate 25000000
set_interface_property VGA_CLK ENABLED true
set_interface_property VGA_CLK EXPORT_OF ""
set_interface_property VGA_CLK PORT_NAME_MAP ""
set_interface_property VGA_CLK CMSIS_SVD_VARIABLES ""
set_interface_property VGA_CLK SVD_ADDRESS_GROUP ""

add_interface_port VGA_CLK VGA_CLK clk Input 1

